<?php
namespace Flux;

class PostType {
	public function __construct() {
		add_action( 'init', [ $this, 'register_post_type' ] );
		add_action( 'init', [ $this, 'register_post_type_rent' ] );
	}
	public function register_post_type() {
		$labels = [ 
			'name'                     => esc_html__( 'Nhà Đất Mua Bán', 'bat-dong-san' ),
			'singular_name'            => esc_html__( 'Nhà đất mua bán', 'bat-dong-san' ),
			'add_new'                  => esc_html__( 'Thêm mới', 'bat-dong-san' ),
			'add_new_item'             => esc_html__( 'Thêm mới nhà đất', 'bat-dong-san' ),
			'edit_item'                => esc_html__( 'Edit nhà đất', 'bat-dong-san' ),
			'new_item'                 => esc_html__( 'New nhà đất', 'bat-dong-san' ),
			'view_item'                => esc_html__( 'Xem nhà đất', 'bat-dong-san' ),
			'view_items'               => esc_html__( 'Xem nhà đất', 'bat-dong-san' ),
			'search_items'             => esc_html__( 'Search nhà đất', 'bat-dong-san' ),
			'not_found'                => esc_html__( 'No nhà đất found.', 'bat-dong-san' ),
			'not_found_in_trash'       => esc_html__( 'No nhà đất found in Trash.', 'bat-dong-san' ),
			'parent_item_colon'        => esc_html__( 'Parent nhà đất:', 'bat-dong-san' ),
			'all_items'                => esc_html__( 'Toàn bộ nhà đất', 'bat-dong-san' ),
			'archives'                 => esc_html__( 'Nhà đất Archives', 'bat-dong-san' ),
			'attributes'               => esc_html__( 'Nhà đất Attributes', 'bat-dong-san' ),
			'insert_into_item'         => esc_html__( 'Insert into nhà đất', 'bat-dong-san' ),
			'uploaded_to_this_item'    => esc_html__( 'Uploaded to this nhà đất', 'bat-dong-san' ),
			'featured_image'           => esc_html__( 'Featured image', 'bat-dong-san' ),
			'set_featured_image'       => esc_html__( 'Set featured image', 'bat-dong-san' ),
			'remove_featured_image'    => esc_html__( 'Remove featured image', 'bat-dong-san' ),
			'use_featured_image'       => esc_html__( 'Use as featured image', 'bat-dong-san' ),
			'menu_name'                => esc_html__( 'Nhà đất mua bán', 'bat-dong-san' ),
			'filter_items_list'        => esc_html__( 'Filter nhà đất list', 'bat-dong-san' ),
			'filter_by_date'           => esc_html__( '', 'bat-dong-san' ),
			'items_list_navigation'    => esc_html__( 'Nhà đất list navigation', 'bat-dong-san' ),
			'items_list'               => esc_html__( 'Nhà đất list', 'bat-dong-san' ),
			'item_published'           => esc_html__( 'Nhà đất published.', 'bat-dong-san' ),
			'item_published_privately' => esc_html__( 'Nhà đất published privately.', 'bat-dong-san' ),
			'item_reverted_to_draft'   => esc_html__( 'Nhà đất reverted to draft.', 'bat-dong-san' ),
			'item_scheduled'           => esc_html__( 'Nhà đất scheduled.', 'bat-dong-san' ),
			'item_updated'             => esc_html__( 'Nhà đất updated.', 'bat-dong-san' ),
		];
		$args   = [ 
			'label'               => esc_html__( 'Nhà đất mua bán', 'bat-dong-san' ),
			'labels'              => $labels,
			'description'         => '',
			'public'              => true,
			'hierarchical'        => false,
			'exclude_from_search' => false,
			'publicly_queryable'  => true,
			'show_ui'             => true,
			'show_in_nav_menus'   => true,
			'show_in_admin_bar'   => true,
			'show_in_rest'        => true,
			'query_var'           => true,
			'can_export'          => true,
			'delete_with_user'    => true,
			'has_archive'         => true,
			'rest_base'           => '',
			'show_in_menu'        => true,
			'menu_position'       => '',
			'menu_icon'           => 'dashicons-store',
			'capability_type'     => 'post',
			'supports'            => [ 'title', 'editor', 'thumbnail' ],
			'taxonomies'          => [],
			'rewrite'             => [ 
				'with_front' => false,
			],
		];

		register_post_type( 'nha-dat-mua-ban', $args );

		$labels2 = [ 
			'name'                       => esc_html__( 'Danh mục mua bán', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Danh mục mua bán', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Danh mục mua bán', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Danh mục', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Danh mục', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Danh mục', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Danh mục', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Danh mục:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Danh mục', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Danh mục', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Danh mục', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Danh mục', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Danh mục Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Danh mục with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Danh mục', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Danh mục', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Danh mục found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Danh mục', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Danh mục', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Danh mục list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Danh mục list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Danh mục', 'bat-dong-san' ),
		];
		$args2   = [ 
			'label'              => esc_html__( 'Danh mục mua bán', 'bat-dong-san' ),
			'labels'             => $labels2,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => false,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];
		register_taxonomy( 'danh-muc-nha-dat', [ 'nha-dat-mua-ban' ], $args2 );

		$labels2 = [ 
			'name'                       => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Quận/Huyện', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Quận/Huyện', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Quận/Huyện', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Quận/Huyện', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Quận/Huyện:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Quận/Huyện', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Quận/Huyện', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Quận/Huyện', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Quận/Huyện', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Quận/Huyện Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Quận/Huyện with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Quận/Huyện', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Quận/Huyện', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Quận/Huyện found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Quận/Huyện', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Quận/Huyện', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Quận/Huyện list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Quận/Huyện list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Quận/Huyện', 'bat-dong-san' ),
		];
		$args2   = [ 
			'label'              => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'labels'             => $labels2,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'dia-diem', [ 'nha-dat-mua-ban' ], $args2 );

		$labels2 = [ 
			'name'                       => esc_html__( 'Diện tích', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Diện tích', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Diện tích', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Diện tích', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Diện tích', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Diện tích', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Diện tích', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Diện tích:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Diện tích', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Diện tích', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Diện tích', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Diện tích', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Diện tích Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Diện tích with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Diện tích', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Diện tích', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Diện tích found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Diện tích', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Diện tích', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Diện tích list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Diện tích list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Diện tích', 'bat-dong-san' ),
		];
		$args2   = [ 
			'label'              => esc_html__( 'Diện tích', 'bat-dong-san' ),
			'labels'             => $labels2,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'dien-tich', [ 'nha-dat-mua-ban' ], $args2 );

		$labels3 = [ 
			'name'                       => esc_html__( 'Giá', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Giá', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Giá', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Giá', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Giá', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Giá', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Giá', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Giá:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Giá', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Giá', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Giá', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Giá', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Giá Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Giá with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Giá', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Giá', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Giá found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Giá', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Giá', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Giá list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Giá list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Giá', 'bat-dong-san' ),
		];
		$args3   = [ 
			'label'              => esc_html__( 'Giá', 'bat-dong-san' ),
			'labels'             => $labels3,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'gia', [ 'nha-dat-mua-ban' ], $args3 );

		$labels4 = [ 
			'name'                       => esc_html__( 'Hướng nhà', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Hướng nhà', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Hướng nhà', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Hướng ', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Hướng ', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Hướng ', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Hướng ', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Hướng :', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Hướng ', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Hướng ', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Hướng ', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Hướng ', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Hướng  Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Hướng  with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Hướng ', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Hướng ', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Hướng  found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Hướng ', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Hướng ', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Hướng  list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Hướng  list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Hướng ', 'bat-dong-san' ),
		];
		$args4   = [ 
			'label'              => esc_html__( 'Hướng nhà ', 'bat-dong-san' ),
			'labels'             => $labels4,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'huong', [ 'nha-dat-mua-ban' ], $args4 );

		$labels5 = [ 
			'name'                       => esc_html__( 'Mặt đường ', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Mặt đường ', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Mặt đường ', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Mặt đường ', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Mặt đường ', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Mặt đường ', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Mặt đường ', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Mặt đường :', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Mặt đường ', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Mặt đường ', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Mặt đường ', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Mặt đường ', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Mặt đường  Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Mặt đường  with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Mặt đường ', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Mặt đường ', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Mặt đường  found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Mặt đường ', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Mặt đường ', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Mặt đường  list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Mặt đường  list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Mặt đường ', 'bat-dong-san' ),
		];
		$args5   = [ 
			'label'              => esc_html__( 'Mặt đường ', 'bat-dong-san' ),
			'labels'             => $labels5,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'mat-duong', [ 'nha-dat-mua-ban' ], $args5 );

		$labels6 = [ 
			'name'                       => esc_html__( 'Phòng ngủ', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Phòng ngủ ', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Phòng ngủ ', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Phòng ngủ ', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Phòng ngủ ', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Phòng ngủ ', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Phòng ngủ ', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Phòng ngủ :', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Phòng ngủ ', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Phòng ngủ ', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Phòng ngủ ', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Phòng ngủ ', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Phòng ngủ  Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Phòng ngủ  with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Phòng ngủ ', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Phòng ngủ ', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Phòng ngủ  found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Phòng ngủ ', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Phòng ngủ ', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Phòng ngủ  list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Phòng ngủ  list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Phòng ngủ ', 'bat-dong-san' ),
		];
		$args6   = [ 
			'label'              => esc_html__( 'Phòng ngủ ', 'bat-dong-san' ),
			'labels'             => $labels6,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'phong-ngu', [ 'nha-dat-mua-ban' ], $args6 );

	}

	public function register_post_type_rent() {
		$labels = [ 
			'name'                     => esc_html__( 'Nhà Đất Cho Thuê', 'bat-dong-san' ),
			'singular_name'            => esc_html__( 'Nhà đất cho thuê', 'bat-dong-san' ),
			'add_new'                  => esc_html__( 'Thêm mới', 'bat-dong-san' ),
			'add_new_item'             => esc_html__( 'Thêm mới nhà đất', 'bat-dong-san' ),
			'edit_item'                => esc_html__( 'Edit nhà đất', 'bat-dong-san' ),
			'new_item'                 => esc_html__( 'New nhà đất', 'bat-dong-san' ),
			'view_item'                => esc_html__( 'Xem nhà đất', 'bat-dong-san' ),
			'view_items'               => esc_html__( 'Xem nhà đất', 'bat-dong-san' ),
			'search_items'             => esc_html__( 'Search nhà đất', 'bat-dong-san' ),
			'not_found'                => esc_html__( 'No nhà đất found.', 'bat-dong-san' ),
			'not_found_in_trash'       => esc_html__( 'No nhà đất found in Trash.', 'bat-dong-san' ),
			'parent_item_colon'        => esc_html__( 'Parent nhà đất:', 'bat-dong-san' ),
			'all_items'                => esc_html__( 'Toàn bộ nhà đất', 'bat-dong-san' ),
			'archives'                 => esc_html__( 'Nhà đất Archives', 'bat-dong-san' ),
			'attributes'               => esc_html__( 'Nhà đất Attributes', 'bat-dong-san' ),
			'insert_into_item'         => esc_html__( 'Insert into nhà đất', 'bat-dong-san' ),
			'uploaded_to_this_item'    => esc_html__( 'Uploaded to this nhà đất', 'bat-dong-san' ),
			'featured_image'           => esc_html__( 'Featured image', 'bat-dong-san' ),
			'set_featured_image'       => esc_html__( 'Set featured image', 'bat-dong-san' ),
			'remove_featured_image'    => esc_html__( 'Remove featured image', 'bat-dong-san' ),
			'use_featured_image'       => esc_html__( 'Use as featured image', 'bat-dong-san' ),
			'menu_name'                => esc_html__( 'Nhà đất cho thuê', 'bat-dong-san' ),
			'filter_items_list'        => esc_html__( 'Filter nhà đất list', 'bat-dong-san' ),
			'filter_by_date'           => esc_html__( '', 'bat-dong-san' ),
			'items_list_navigation'    => esc_html__( 'Nhà đất list navigation', 'bat-dong-san' ),
			'items_list'               => esc_html__( 'Nhà đất list', 'bat-dong-san' ),
			'item_published'           => esc_html__( 'Nhà đất published.', 'bat-dong-san' ),
			'item_published_privately' => esc_html__( 'Nhà đất published privately.', 'bat-dong-san' ),
			'item_reverted_to_draft'   => esc_html__( 'Nhà đất reverted to draft.', 'bat-dong-san' ),
			'item_scheduled'           => esc_html__( 'Nhà đất scheduled.', 'bat-dong-san' ),
			'item_updated'             => esc_html__( 'Nhà đất updated.', 'bat-dong-san' ),
		];
		$args   = [ 
			'label'               => esc_html__( 'Nhà đất cho thuê', 'bat-dong-san' ),
			'labels'              => $labels,
			'description'         => '',
			'public'              => true,
			'hierarchical'        => false,
			'exclude_from_search' => false,
			'publicly_queryable'  => true,
			'show_ui'             => true,
			'show_in_nav_menus'   => true,
			'show_in_admin_bar'   => true,
			'show_in_rest'        => true,
			'query_var'           => true,
			'can_export'          => true,
			'delete_with_user'    => true,
			'has_archive'         => true,
			'rest_base'           => '',
			'show_in_menu'        => true,
			'menu_position'       => '',
			'menu_icon'           => 'dashicons-store',
			'capability_type'     => 'post',
			'supports'            => [ 'title', 'editor', 'thumbnail' ],
			'taxonomies'          => [],
			'rewrite'             => [ 
				'with_front' => false,
			],
		];

		register_post_type( 'nha-dat-cho-thue', $args );

		$labels2 = [ 
			'name'                       => esc_html__( 'Danh mục cho thuê', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Danh mục cho thuê', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Danh mục cho thuê', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Danh mục', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Danh mục', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Danh mục', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Danh mục', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Danh mục:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Danh mục', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Danh mục', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Danh mục', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Danh mục', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Danh mục Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Danh mục with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Danh mục', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Danh mục', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Danh mục found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Danh mục', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Danh mục', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Danh mục list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Danh mục list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Danh mục', 'bat-dong-san' ),
		];
		$args2   = [ 
			'label'              => esc_html__( 'Danh mục', 'bat-dong-san' ),
			'labels'             => $labels2,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => false,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];
		register_taxonomy( 'danh-muc-cho-thue', [ 'nha-dat-cho-thue' ], $args2 );

		$labels3 = [ 
			'name'                       => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Quận/Huyện', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Quận/Huyện', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Quận/Huyện', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Quận/Huyện', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Quận/Huyện:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Quận/Huyện', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Quận/Huyện', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Quận/Huyện', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Quận/Huyện', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Quận/Huyện Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Quận/Huyện with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Quận/Huyện', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Quận/Huyện', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Quận/Huyện found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Quận/Huyện', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Quận/Huyện', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Quận/Huyện list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Quận/Huyện list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Quận/Huyện', 'bat-dong-san' ),
		];
		$args3   = [ 
			'label'              => esc_html__( 'Quận/Huyện', 'bat-dong-san' ),
			'labels'             => $labels3,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => false,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];
		register_taxonomy( 'dia-diem-rent', [ 'nha-dat-cho-thue' ], $args3 );

		$labels4 = [ 
			'name'                       => esc_html__( 'Giá', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Giá', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Giá', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Giá', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Giá', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Giá', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Giá', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Giá:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Giá', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Giá', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Giá', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Giá', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Giá Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Giá with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Giá', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Giá', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Giá found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Giá', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Giá', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Giá list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Giá list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Giá', 'bat-dong-san' ),
		];
		$args4   = [ 
			'label'              => esc_html__( 'Giá', 'bat-dong-san' ),
			'labels'             => $labels4,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'gia-rent', [ 'nha-dat-cho-thue' ], $args4 );

		$labels5 = [ 
			'name'                       => esc_html__( 'Hướng nhà', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Hướng nhà', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Hướng nhà', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Hướng ', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Hướng ', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Hướng ', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Hướng ', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Hướng :', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Hướng ', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Hướng ', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Hướng ', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Hướng ', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Hướng  Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Hướng  with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Hướng ', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Hướng ', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Hướng  found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Hướng ', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Hướng ', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Hướng  list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Hướng  list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Hướng ', 'bat-dong-san' ),
		];
		$args5   = [ 
			'label'              => esc_html__( 'Hướng nhà ', 'bat-dong-san' ),
			'labels'             => $labels5,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'huong-rent', [ 'nha-dat-cho-thue' ], $args5 );

		$labels6 = [ 
			'name'                       => esc_html__( 'Phòng ngủ', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Phòng ngủ ', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Phòng ngủ ', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Phòng ngủ ', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Phòng ngủ ', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Phòng ngủ ', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Phòng ngủ ', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Phòng ngủ :', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Phòng ngủ ', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Phòng ngủ ', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Phòng ngủ ', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Phòng ngủ ', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Phòng ngủ  Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Phòng ngủ  with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Phòng ngủ ', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Phòng ngủ ', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Phòng ngủ  found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Phòng ngủ ', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Phòng ngủ ', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Phòng ngủ  list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Phòng ngủ  list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Phòng ngủ ', 'bat-dong-san' ),
		];
		$args6   = [ 
			'label'              => esc_html__( 'Phòng ngủ ', 'bat-dong-san' ),
			'labels'             => $labels6,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'phong-ngu-rent', [ 'nha-dat-cho-thue' ], $args6 );

		$labels7 = [ 
			'name'                       => esc_html__( 'Thang máy', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Thang máy ', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Thang máy ', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Thang máy ', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Thang máy', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Thang máy', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Thang máy', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Thang máy :', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Thang máy ', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Thang máy', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Thang máy', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Thang máy', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Thang máy Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Thang máy with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Thang máy', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Thang máy', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Thang máy found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Thang máy', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Thang máy', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Thang máy list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Thang máy list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Thang máy', 'bat-dong-san' ),
		];
		$args7   = [ 
			'label'              => esc_html__( 'Thang máy', 'bat-dong-san' ),
			'labels'             => $labels7,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => true,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];

		register_taxonomy( 'thang-may-rent', [ 'nha-dat-cho-thue' ], $args7 );

		//Dự án postype
		$labels = [ 
			'name'                     => esc_html__( 'Dự Án', 'bat-dong-san' ),
			'singular_name'            => esc_html__( 'Dự Án', 'bat-dong-san' ),
			'add_new'                  => esc_html__( 'Thêm mới', 'bat-dong-san' ),
			'add_new_item'             => esc_html__( 'Thêm mới dự án', 'bat-dong-san' ),
			'edit_item'                => esc_html__( 'Edit dự án', 'bat-dong-san' ),
			'new_item'                 => esc_html__( 'New dự án', 'bat-dong-san' ),
			'view_item'                => esc_html__( 'Xem dự án', 'bat-dong-san' ),
			'view_items'               => esc_html__( 'Xem dự án', 'bat-dong-san' ),
			'search_items'             => esc_html__( 'Search dự án', 'bat-dong-san' ),
			'not_found'                => esc_html__( 'No dự án found.', 'bat-dong-san' ),
			'not_found_in_trash'       => esc_html__( 'No dự án found in Trash.', 'bat-dong-san' ),
			'parent_item_colon'        => esc_html__( 'Parent dự án:', 'bat-dong-san' ),
			'all_items'                => esc_html__( 'Toàn bộ dự án', 'bat-dong-san' ),
			'archives'                 => esc_html__( 'Dự án Archives', 'bat-dong-san' ),
			'attributes'               => esc_html__( 'Dự án Attributes', 'bat-dong-san' ),
			'insert_into_item'         => esc_html__( 'Insert into dự án', 'bat-dong-san' ),
			'uploaded_to_this_item'    => esc_html__( 'Uploaded to this dự án', 'bat-dong-san' ),
			'featured_image'           => esc_html__( 'Featured image', 'bat-dong-san' ),
			'set_featured_image'       => esc_html__( 'Set featured image', 'bat-dong-san' ),
			'remove_featured_image'    => esc_html__( 'Remove featured image', 'bat-dong-san' ),
			'use_featured_image'       => esc_html__( 'Use as featured image', 'bat-dong-san' ),
			'menu_name'                => esc_html__( 'Dự án', 'bat-dong-san' ),
			'filter_items_list'        => esc_html__( 'Filter dự án list', 'bat-dong-san' ),
			'filter_by_date'           => esc_html__( '', 'bat-dong-san' ),
			'items_list_navigation'    => esc_html__( 'Dự án list navigation', 'bat-dong-san' ),
			'items_list'               => esc_html__( 'Dự án list', 'bat-dong-san' ),
			'item_published'           => esc_html__( 'Dự án published.', 'bat-dong-san' ),
			'item_published_privately' => esc_html__( 'Dự án published privately.', 'bat-dong-san' ),
			'item_reverted_to_draft'   => esc_html__( 'Dự án reverted to draft.', 'bat-dong-san' ),
			'item_scheduled'           => esc_html__( 'Dự án scheduled.', 'bat-dong-san' ),
			'item_updated'             => esc_html__( 'Dự án updated.', 'bat-dong-san' ),
		];
		$args   = [ 
			'label'               => esc_html__( 'Dự án', 'bat-dong-san' ),
			'labels'              => $labels,
			'description'         => '',
			'public'              => true,
			'hierarchical'        => false,
			'exclude_from_search' => false,
			'publicly_queryable'  => true,
			'show_ui'             => true,
			'show_in_nav_menus'   => true,
			'show_in_admin_bar'   => true,
			'show_in_rest'        => true,
			'query_var'           => true,
			'can_export'          => true,
			'delete_with_user'    => true,
			'has_archive'         => true,
			'rest_base'           => '',
			'show_in_menu'        => true,
			'menu_position'       => '',
			'menu_icon'           => 'dashicons-store',
			'capability_type'     => 'post',
			'supports'            => [ 'title', 'editor', 'thumbnail' ],
			'taxonomies'          => [],
			'rewrite'             => [ 
				'with_front' => false,
			],
		];

		register_post_type( 'du-an', $args );

		//Danh mục dự án
		$labels2 = [ 
			'name'                       => esc_html__( 'Danh mục dự án', 'bat-dong-san' ),
			'singular_name'              => esc_html__( 'Danh mục dự án', 'bat-dong-san' ),
			'menu_name'                  => esc_html__( 'Danh mục dự án', 'bat-dong-san' ),
			'search_items'               => esc_html__( 'Search Danh mục', 'bat-dong-san' ),
			'popular_items'              => esc_html__( 'Popular Danh mục', 'bat-dong-san' ),
			'all_items'                  => esc_html__( 'All Danh mục', 'bat-dong-san' ),
			'parent_item'                => esc_html__( 'Parent Danh mục', 'bat-dong-san' ),
			'parent_item_colon'          => esc_html__( 'Parent Danh mục:', 'bat-dong-san' ),
			'edit_item'                  => esc_html__( 'Edit Danh mục', 'bat-dong-san' ),
			'view_item'                  => esc_html__( 'View Danh mục', 'bat-dong-san' ),
			'update_item'                => esc_html__( 'Update Danh mục', 'bat-dong-san' ),
			'add_new_item'               => esc_html__( 'Add New Danh mục', 'bat-dong-san' ),
			'new_item_name'              => esc_html__( 'New Danh mục Name', 'bat-dong-san' ),
			'separate_items_with_commas' => esc_html__( 'Separate Danh mục with commas', 'bat-dong-san' ),
			'add_or_remove_items'        => esc_html__( 'Add or remove Danh mục', 'bat-dong-san' ),
			'choose_from_most_used'      => esc_html__( 'Choose most used Danh mục', 'bat-dong-san' ),
			'not_found'                  => esc_html__( 'No Danh mục found.', 'bat-dong-san' ),
			'no_terms'                   => esc_html__( 'No Danh mục', 'bat-dong-san' ),
			'filter_by_item'             => esc_html__( 'Filter by Danh mục', 'bat-dong-san' ),
			'items_list_navigation'      => esc_html__( 'Danh mục list pagination', 'bat-dong-san' ),
			'items_list'                 => esc_html__( 'Danh mục list', 'bat-dong-san' ),
			'most_used'                  => esc_html__( 'Most Used', 'bat-dong-san' ),
			'back_to_items'              => esc_html__( '&larr; Go to Danh mục', 'bat-dong-san' ),
		];
		$args2   = [ 
			'label'              => esc_html__( 'Danh mục dự án', 'bat-dong-san' ),
			'labels'             => $labels2,
			'description'        => '',
			'public'             => true,
			'publicly_queryable' => true,
			'hierarchical'       => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,
			'show_in_rest'       => true,
			'show_tagcloud'      => true,
			'show_in_quick_edit' => true,
			'show_admin_column'  => true,
			'query_var'          => true,
			'sort'               => false,
			'meta_box_cb'        => 'post_categories_meta_box',
			'rest_base'          => '',
			'rewrite'            => [ 
				'with_front'   => false,
				'hierarchical' => false,
			],
		];
		register_taxonomy( 'danh-muc-du-an', [ 'du-an' ], $args2 );
	}

}